package org.omg.PortableServer;


/**
* org/omg/PortableServer/ID_UNIQUENESS_POLICY_ID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /HUDSON/workspace/8-2-build-linux-amd64/jdk8u72/5732/corba/src/share/classes/org/omg/PortableServer/poa.idl
* Tuesday, December 22, 2015 10:00:45 PM PST
*/

public interface ID_UNIQUENESS_POLICY_ID
{

  /**
  	 * The value representing ID_UNIQUENESS_POLICY_ID.
  	 */
  public static final int value = (int)(18L);
}
